

listindexing2.svg: listindexing2.pdf
	pdf2svg listindexing2.pdf listindexing2.svg

listindexing1.svg: listindexing1.pdf
	pdf2svg listindexing1.pdf listindexing1.svg

arraygraphics_6.svg: arraygraphics_6.pdf
	pdf2svg arraygraphics_6.pdf arraygraphics_6.svg

arraygraphics_7.svg: arraygraphics_7.pdf
	pdf2svg arraygraphics_7.pdf arraygraphics_7.svg

broadcast.svg: broadcast.pdf
	pdf2svg broadcast.pdf broadcast.svg
