# https://stackoverflow.com/a/32670466/5766934
# https://stackoverflow.com/a/16481079/5766934

numpy_array_t.png: numpy_array.png
	convert numpy_array.png -transparent white numpy_array_t.png

numpy-reshape-examples_t.png: numpy-reshape-examples.jpg
	convert numpy-reshape-examples.jpg -fuzz 5% -transparent white numpy-reshape-examples_t.png

numpy-slice_t.png: numpy-slice.jpg
	convert numpy-slice.jpg -fuzz 5% -transparent white numpy-slice_t.png
